(define-module (jlife main)
  #:use-module (jlib parse)
  #:use-module (jlife dateparser)
  #:use-module (jlife durationparser)
  #:use-module (jlife repetitionparser)
  #:use-module (jlib print))


(parameterize ((ignore-case #t)) 
  (println ((parse/time) "tomorrow@8am"))
  (println ((parse/time) "dec8@8am"))
  (println ((parse/time) "10:45pm"))
  (println ((parse/time) "11"))
  (println ((parse/time) "tu"))
  (println ((parse/time) "we"))

  (println ((parse/duration) "30m"))
  (println ((parse/duration) "2houRs"))

  (println ((parse/repeats) "MoWeFr"))
  (println ((parse/repeats) "Daily"))
  (println ((parse/repeats) "Weekly"))
  (println ((parse/repeats) "Monthly"))
  (println ((parse/repeats) "Yearly"))
  (println ((parse/repeats) "4days"))
  (println ((parse/repeats) "2weeks")))
