(define-module (jlife profile)
  #:use-module (jlib print)
  #:use-module (jlib shell)
  #:use-module (jlib strings)
  #:use-module (jlife config)
  #:use-module (jlife backend)
  #:use-module (jlife frontend)
  #:export (profile-add
            profile-remove
            profile-use
            profile-list
            profile-current))

(define (profile-list)
  (define d (opendir (store-path)))
  (define (loop)
    (define entry (readdir d))
    (unless (eof-object? entry)
      (when (starts-with entry "data-")
        (let ((prof (substring entry 5)))
          (if (string=? (profile-current) prof)
            (println prof)
            (with-effect #:BOLD (println prof)))))
      (loop)))
  (loop))

(define (profile-add p)
  (when (has-profile p)
    (println (string-append "Profile " p " already exists")))
  (unless (has-profile p)
    (println (string-append "Added profile " p))
    (call-with-output-file (profile-path p)
      (lambda (port)
        (write '() port)))
    (call-with-output-file (profile-diff-path p)
      (lambda (port)
        (write '() port)))))

(define (profile-rm p)
  (unless (has-profile p)
    (println (string-append "Failed to find profile " p)))
  (when (has-profile p)
    (println (string-append "Removing profile " p))
    (delete-file (profile-path p))
    (delete-file (profile-diff-path p))))

(define (profile-use p)
  (unless (has-profile p)
    (println (string-append "Failed to find profile " p)))
  (when (has-profile p)
    (println (string-append "Using profile " p))
    (delete-file (profile-path ""))
    (symlink (profile-path p) (profile-path ""))
    (delete-file (profile-diff-path ""))
    (symlink (profile-diff-path p) (profile-diff-path ""))))

(define (profile-path p)
  (p-path p "data"))
(define (profile-diff-path p)
  (p-path p "diff"))
(define (p-path p word)
  (define pre (string-append (store-path) word))
  (if (= 0 (string-length p))
    pre (string-append pre "-" p)))

(define (has-profile p)
  (file-exists? (profile-path p)))

(define (profile-current)
  (substring (car (reverse (string-split (readlink (profile-path "")) #\/))) 5))

