(define-module (jlife server)
  #:use-module (jlib print)
  #:use-module (jlib files)
  #:use-module (jlib lists)
  #:use-module (jlife events)
  #:use-module (jlife config)
  #:use-module (jlife backend)
  #:use-module (jlife diff-data)
  #:use-module (json)
  #:use-module (schingle content-type)
  #:use-module (schingle static)
  #:use-module (schingle handler)
  #:use-module (schingle query)
  #:use-module (schingle template)
  #:use-module (schingle middleware)
  #:use-module (schingle schingle))

(define data-path "/home/jacob/.jlife/server/")

(GET "/data/:uid"
     (lambda* (request body #:key :uid)
      (define loc (getenv "JLIFE_LOCATION"))
      (setenv "JLIFE_LOCATION" (string-append data-path :uid "/"))
      (let ((data (load-data)))
        (setenv "JLIFE_LOCATION" loc)
        (json `((error . #f) (data . ,(event-list->json-scm data)))))))

(POST "/data"
      (lambda (request body)
        (define diff (json-string->event-list (assoc-ref body "diff")))
        (define :uid (assoc-ref body "uid"))
        (define loc (getenv "JLIFE_LOCATION"))
        (setenv "JLIFE_LOCATION" (string-append data-path :uid "/"))
        (let* ((data (load-data))
               (new-data (process-diffs-on-master diff data)))
          (save-data new-data)
          (setenv "JLIFE_LOCATION" loc)
          (json `((error . #f) (data . ,(event-list->json-scm new-data)))))))

(POST "/data-replace"
      (lambda (request body)
        (define jbody (json-string->scm body))
        (define uid (assoc-get "uid" jbody))
        (define data (assoc-get "data" jbody))
        (define events (map json-scm->event (vector->list data)))
        (define loc (getenv "JLIFE_LOCATION"))
        (setenv "JLIFE_LOCATION" (string-append data-path uid "/"))
        ;(save-data new-data)
        (writeln events)
        (setenv "JLIFE_LOCATION" loc)
        (json `((error . #f) (data . ,(event-list->json-scm events))))))

(define (custom404 request body)
  (json '((error . not-found))))

(define (main)
  (println "Server Started")
  (mkdir-if data-path)
  (run-schingle #:h404 custom404))
(main)
